#!/bin/bash
# Regenerate .mwp/FEATURE_PRIORITY_REGISTRY.md from each feature's own
# FEATURE_META.md. This registry is a computed, disposable view — never
# hand-edit it. Edit a feature's FEATURE_META.md and re-run this script
# instead. See docs/evolution/0003-computed-priority-registry.md.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FEATURES_DIR="$ROOT_DIR/features"
OUT_FILE="$ROOT_DIR/.mwp/FEATURE_PRIORITY_REGISTRY.md"

# shellcheck source=lib/scan_features.sh
source "$SCRIPT_DIR/lib/scan_features.sh"
# shellcheck source=lib/log.sh
source "$SCRIPT_DIR/lib/log.sh"
trap 'LOG_EXIT_CODE=$?; log_invocation "$ROOT_DIR" "$(basename "$0")" "$*" "$LOG_EXIT_CODE"' EXIT

get_field() {
  grep -E "^${2}:" "$1" 2>/dev/null | head -1 | sed -E "s/^${2}:[[:space:]]*//"
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  echo "Usage: $0"
  echo "Regenerate .mwp/FEATURE_PRIORITY_REGISTRY.md from every feature's FEATURE_META.md."
  echo "Takes no arguments. Never hand-edit the registry; edit FEATURE_META.md instead."
  exit 0
fi

mkdir -p "$ROOT_DIR/.mwp"

ANCHOR_ROWS=()
ACTIVE_ROWS=()
DEEP_ROWS=()
UNSCORED_ROWS=()
MALFORMED_ROWS=()

while IFS= read -r FEATURE_DIR; do
  meta="$FEATURE_DIR/FEATURE_META.md"
  [ -f "$meta" ] || continue
  REL_PATH="./features/$(basename "$FEATURE_DIR")"

  FID=$(get_field "$meta" "feature_id"); [ -z "$FID" ] && FID="$(basename "$FEATURE_DIR")"
  NAME=$(get_field "$meta" "name")
  C=$(get_field "$meta" "c")
  V=$(get_field "$meta" "v")
  R=$(get_field "$meta" "r")
  STATUS=$(get_field "$meta" "status"); [ -z "$STATUS" ] && STATUS="not started"
  ANCHOR=$(get_field "$meta" "is_core_anchor")

  if [ "$ANCHOR" = "true" ]; then
    ANCHOR_ROWS+=("| $FID | $NAME | $STATUS | \`$REL_PATH\` |")
    continue
  fi

  if [ -z "$C" ] || [ -z "$V" ] || [ -z "$R" ]; then
    UNSCORED_ROWS+=("| $FID | $NAME | $STATUS | \`$REL_PATH\` |")
    continue
  fi

  # --- C/V/R contract validation (entry 0039) ---
  # All three fields are present at this point (the blank check above already
  # routed away anything missing a field) -- but present doesn't mean valid.
  # docs/PRIORITIZATION_GUIDE.md's contract is an integer 1-5 for each. A
  # non-numeric or out-of-range value would otherwise silently compute as a
  # SCORE of 0 via awk's arithmetic coercion just below (a non-numeric string
  # coerces to 0 in awk arithmetic context) -- indistinguishable from a
  # legitimately low-priority feature. Route it to its own bucket instead so
  # a human sees *why* it isn't scored, not just that the score happens to be
  # rock-bottom.
  BAD_FIELDS=""
  [[ "$C" =~ ^[1-5]$ ]] || BAD_FIELDS="${BAD_FIELDS}c=\"$C\" "
  [[ "$V" =~ ^[1-5]$ ]] || BAD_FIELDS="${BAD_FIELDS}v=\"$V\" "
  [[ "$R" =~ ^[1-5]$ ]] || BAD_FIELDS="${BAD_FIELDS}r=\"$R\" "

  if [ -n "$BAD_FIELDS" ]; then
    MALFORMED_ROWS+=("| $FID | $NAME | $STATUS | \`$REL_PATH\` | ${BAD_FIELDS% } |")
    continue
  fi

  SCORE=$(awk -v c="$C" -v v="$V" -v r="$R" 'BEGIN { if (r+0 == 0) print "0"; else printf "%.1f", (c*v)/r }')
  ROW="| $FID | $NAME | $C | $V | $R | $SCORE | $STATUS | \`$REL_PATH\` |"

  if [ "${R%.*}" -ge 4 ] 2>/dev/null; then
    DEEP_ROWS+=("$SCORE"$'\t'"$ROW")
  else
    ACTIVE_ROWS+=("$SCORE"$'\t'"$ROW")
  fi
done < <(list_workspace_dirs "$FEATURES_DIR")

sorted() {
  # Sort tab-prefixed "score\trow" entries by score descending, print rows only.
  if [ "$#" -eq 0 ]; then return; fi
  printf '%s\n' "$@" | sort -t$'\t' -k1,1 -rn | cut -f2-
}

{
  echo "# Feature Priority Registry"
  echo ""
  echo "<!-- GENERATED by scripts/registry.sh — do not hand-edit. Edit each feature's FEATURE_META.md and re-run this script instead. See docs/evolution/0003-computed-priority-registry.md. -->"
  echo ""
  echo "## Phase 0 — Core Data Anchors (bypass C-V-R scoring, run first, unconditionally)"
  echo ""
  echo "| Feature ID | Name | Status | Workspace Path |"
  echo "|---|---|---|---|"
  if [ "${#ANCHOR_ROWS[@]}" -gt 0 ]; then printf '%s\n' "${ANCHOR_ROWS[@]}"; else echo "| — | — | — | — |"; fi
  echo ""
  echo "## Active execution queue (scored, C-V-R = (C × V) / R)"
  echo ""
  echo "| Feature ID | Name | C | V | R | Score | Status | Workspace Path |"
  echo "|---|---|---|---|---|---|---|---|"
  if [ "${#ACTIVE_ROWS[@]}" -gt 0 ]; then sorted "${ACTIVE_ROWS[@]}"; else echo "| — | — | — | — | — | — | queued | — |"; fi
  echo ""
  echo "## Deep context backlog (R >= 4 — sequential, human-gated, not parallelized)"
  echo ""
  echo "| Feature ID | Name | C | V | R | Score | Status | Notes |"
  echo "|---|---|---|---|---|---|---|---|"
  if [ "${#DEEP_ROWS[@]}" -gt 0 ]; then sorted "${DEEP_ROWS[@]}"; else echo "| — | — | — | — | — | — | blocked | — |"; fi
  if [ "${#UNSCORED_ROWS[@]}" -gt 0 ]; then
    echo ""
    echo "## Not yet scored"
    echo ""
    echo "| Feature ID | Name | Status | Workspace Path |"
    echo "|---|---|---|---|"
    printf '%s\n' "${UNSCORED_ROWS[@]}"
  fi
  if [ "${#MALFORMED_ROWS[@]}" -gt 0 ]; then
    echo ""
    echo "## Malformed (needs attention)"
    echo ""
    echo "<!-- C/V/R present but not a valid 1-5 integer per docs/PRIORITIZATION_GUIDE.md -- entry 0039. Fix the listed field(s) in FEATURE_META.md and re-run registry.sh. -->"
    echo ""
    echo "| Feature ID | Name | Status | Workspace Path | Invalid field(s) |"
    echo "|---|---|---|---|---|"
    printf '%s\n' "${MALFORMED_ROWS[@]}"
  fi
  echo ""
  echo "## Rules"
  echo ""
  echo "1. Core Data Anchors always run first and are never scored."
  echo "2. Features with R >= 4 move to the Deep Context Backlog and run sequentially with mandatory human review at every stage gate — never in parallel with other features touching the same subsystem."
  echo "3. Everything else runs in the Active Execution Queue, highest score first, and can be parallelized across separate terminal/agent sessions since Micro-PDLC isolates each feature's folder."
  echo "4. A Malformed feature is excluded from scoring entirely (not scored as 0) until its C/V/R fields are fixed to valid 1-5 integers."
} > "$OUT_FILE"

TOTAL=$(( ${#ANCHOR_ROWS[@]} + ${#ACTIVE_ROWS[@]} + ${#DEEP_ROWS[@]} + ${#UNSCORED_ROWS[@]} + ${#MALFORMED_ROWS[@]} ))
echo "Regenerated $OUT_FILE from $TOTAL feature(s)."
